#!/usr/bin/env bash
# Bash script for setting up an Nginx server with a custom header.
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sed -i '/server_name _;/a \
    rewrite ^/redirect_me https://github.com/ichebadu permanent;\
\n\n\terror_page 404 /custom_404.html;\
\n\tlocation = /custom_404.html {\
\n\t\troot /usr/share/nginx/html;\
\n\t\tinternal;\
\n\t}' /etc/nginx/sites-available/default

sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/a \
    add_header X-Served-By "$HOSTNAME";' /etc/nginx/nginx.conf

service nginx start
