#!/usr/bin/env bash
#Installs and sets up HAProxy load balancer for web servers

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.*

echo "ENABLED=1" > /etc/default/haproxy

echo "
listen load_balancer
bind *:80
mode http
balance roundrobin
option httpclose
option forwardfor
server :80 check
server :80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
